;AUTO GENERATED
[Fdr0_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr0Group

[Fdr0_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr0Group

[Fdr0_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr0Group

[Fdr0_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr0Group

[Fdr0_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr0Group

[Fdr0_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr0Group

[Fdr0_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr0Group

[Fdr0_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr0Group
