;AUTO GENERATED
[Fdr1_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr1Group

[Fdr1_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_6Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_6]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_7Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_7]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group

[Fdr1_8Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr1Group

[Fdr1_8]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr1Group
