;AUTO GENERATED
[Fdr2_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr2Group

[Fdr2_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_6Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_6]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_7Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_7]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_8Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_8]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group

[Fdr2_9Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr2Group

[Fdr2_9]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr2Group
