;AUTO GENERATED
[Fdr3_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr3Group

[Fdr3_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_6Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_6]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_7Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_7]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_8Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_8]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_9Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_9]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_10Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_10]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_11Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_11]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_12Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_12]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_13Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_13]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_14Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_14]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_15Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_15]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_16Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_16]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group

[Fdr3_17Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr3Group

[Fdr3_17]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr3Group
