;AUTO GENERATED
[Fdr4_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr4Group

[Fdr4_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr4Group

[Fdr4_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr4Group

[Fdr4_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr4Group

[Fdr4_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr4Group

[Fdr4_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr4Group

[Fdr4_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr4Group

[Fdr4_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr4Group
