;AUTO GENERATED
[Fdr5_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr5Group

[Fdr5_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_6Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_6]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_7Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_7]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_8Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_8]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_9Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_9]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_10Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_10]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_11Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_11]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_12Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_12]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_13Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_13]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_14Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_14]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_15Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_15]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_16Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_16]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_17Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_17]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group

[Fdr5_18Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr5Group

[Fdr5_18]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr5Group
