;AUTO GENERATED
[Fdr6_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr6Group

[Fdr6_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_6Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_6]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group

[Fdr6_7Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr6Group

[Fdr6_7]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr6Group
