;AUTO GENERATED
[Fdr7_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr7Group

[Fdr7_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_3Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_3]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_4Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_4]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group

[Fdr7_5Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr7Group

[Fdr7_5]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr7Group
