;AUTO GENERATED
[Fdr8_0Image]
Meter=Image
MeterStyle=SItemImage | SItemHeadLocate | SFdr8Group

[Fdr8_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr8Group

[Fdr8_0Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr8Group

[Fdr8_0]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr8Group

[Fdr8_1Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr8Group

[Fdr8_1]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr8Group

[Fdr8_2Image]
Meter=Image
MeterStyle=SItemImage | SItemImageLocate | SFdr8Group

[Fdr8_2]
Meter=String
MeterStyle=SItemText | SItemTextLocate | SFolderFont | SFdr8Group
