;AUTO GENERATED
[Fdr0Image]
Meter=Image
MeterStyle=SFolderImage | SFolderHeadLocate | SExpandedGroup

[Fdr0]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr1Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr1]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr2Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr2]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr3Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr3]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr4Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr4]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr5Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr5]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr6Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr6]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr7Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr7]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup

[Fdr8Image]
Meter=Image
MeterStyle=SFolderImage | SFolderImageLocate | SExpandedGroup

[Fdr8]
Meter=String
MeterStyle=SFolderText | SFolderTextLocate | SFolderFont | SExpandedGroup
